---
title: "Sample Sizes By Ecoregion"
date: "5/5/2020"
output: word_document
---

```{r samplesize_meta, echo = FALSE, include = FALSE}
library(tidyverse)
library(ggplot2)
# Sample size histogram

## Read in sample size csv
SampleSize <- read.csv(file = "Ecoregion_SampleSizes.csv", stringsAsFactors = FALSE)
SampleSize$Year <- gsub("2012" , "2013", SampleSize$Year)

cc2 <- scales::seq_gradient_pal("grey", "dodgerblue2", "Lab")(seq(0,1,length.out = (length(unique(SampleSize$Year))))) 

SampleSizeHist <- SampleSize %>% filter(!Ecoregion == "Marine West Coast Forest") %>%
  mutate(Year = fct_relevel(Year, "2018", "2017","2016", "2015" , "2014" , "2013" , "2011")) %>%
            mutate(Ecoregion = fct_relevel(Ecoregion, "West-Central Semi-Arid Prairies", "Western Cordillera", "Warm Deserts", "South-Central Semi-Arid Prairies","Northern Cold Deserts", "Mediterranean California", "Madrean Archipelago", "Eastern Cold Deserts", "Central Basin and Range", "Arizona/ New Mexico Mountains" , 
 "All BLM Range")) %>% 
  ggplot(aes(x = Ecoregion, y = BLM.Sample, fill = Year)) +
                  geom_bar(aes(x = Ecoregion, y = BLM.Sample), stat = "identity", position = position_dodge2(1)) + labs(y = "Number of observed points in BLM Range") + 
                  theme(strip.text.x = element_text(size = 12 , color = "black" , face = "bold") , panel.background = element_rect(fill = "white") , 
                 panel.grid = element_line(color = "grey") ,
                 panel.grid.minor = element_blank() , 
                 panel.grid.major.x = element_line(color = "grey95"), 
                 axis.title.x = element_text(size = 12), 
                 axis.title.y = element_blank(), 
                 axis.text.x = element_text(size = 12.5) , 
                 axis.text.y = element_text(size = 12.5), 
                 legend.text = element_text(size = 12), 
                 legend.title = element_text(size = 12) , 
                 legend.position = "bottom", 
                 legend.justification = "right") +
                 coord_flip() +  
                 scale_fill_manual(values=cc2, guide = guide_legend(reverse=TRUE))
```

```{r print sample, echo=FALSE, include = TRUE, fig.height = 10 , fig.width = 9.5}

SampleSizeHist

```